<<<<<<< HEAD
name: Flood Detection Pipeline

on:
  workflow_dispatch:
  schedule:
    # Runs at 1:30 AM UTC, which is 7:00 AM in Indian Standard Time (IST)
    - cron: '30 1 * * *'

jobs:
  build-and-run:
    # --- THIS IS THE KEY CHANGE ---
    # We are now using a standard Ubuntu Linux virtual machine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
=======
# .github/workflows/main.yml
name: Daily Flood Detector

on:
  # This adds the "Run workflow" button for your one-time test run
  workflow_dispatch:
  
  # This is the automatic schedule for the daily deployment
  schedule:
    # Runs at 01:30 UTC, which is 7:00 AM IST
    - cron: '30 1 * * *'

jobs:
  run-flood-detector:
    # Use the efficient Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository and downloads your large LFS files
      - name: Check out repository
>>>>>>> 3676517252cd846a1a8d7011df9b892957423902
        uses: actions/checkout@v4
        with:
          lfs: true

<<<<<<< HEAD
=======
      # Step 2: Sets up Python
>>>>>>> 3676517252cd846a1a8d7011df9b892957423902
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      # Step 3: Installs the GDAL library, which is required on Ubuntu
      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

<<<<<<< HEAD
      - name: Install System Dependencies for GDAL on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Install Python Libraries
        run: pip install -r requirements.txt

      - name: Run the Flood Detection Pipeline
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python watcher.py
=======
      # Step 4: Installs all your Python libraries from requirements.txt
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Step 5: Runs your pipeline script once from start to finish
      - name: Run Flood Detection Pipeline
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python3 watcher.py
>>>>>>> 3676517252cd846a1a8d7011df9b892957423902
