name: Flood Detection Pipeline

on:
  workflow_dispatch:
  schedule:
    # Runs at 1:30 AM UTC, which is 7:00 AM in Indian Standard Time (IST)
    - cron: '30 1 * * *'

jobs:
  build-and-run:
    # --- THIS IS THE KEY CHANGE ---
    # We are now using a standard Ubuntu Linux virtual machine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies for GDAL on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Install Python Libraries
        run: pip install -r requirements.txt

      - name: Run the Flood Detection Pipeline
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python watcher.py